### ISSUE TITLE
Instead of environment variables, consider a humble config file

### ISSUE THREAD

**Issue by mckern** [stahnma/vmpool-cli#5]
Because putting passwords into an environment variable is kind of scary.

**Comment by stahnma** [comment]
Why? Having them in a config file means they're in plain text and they're loadable in memory. In environment variables you can just have them in memory.

**Comment by mckern** [comment]
I'd rather they never get stored at all, and that just the token is saved. Config file would also let you do things like easily save/swap the VM Pooler URL.

Config files > Env. variables, 99% of the time.

**Comment by stahnma** [comment]
Just pushed 0.2.2 about 90 minutes ago. That has the VMPOOL_TOKEN fix so you don't need to auth if you have a token.
