### ISSUE TITLE
Better document what the `vm` subcommand does

### ISSUE THREAD

**Issue by mckern** [stahnma/vmpool-cli#6]
Because I haven't got any idea

**Comment by stahnma** [comment]
./vmpool help vm

**Comment by stahnma** [comment]
also man vmpool

**Comment by stahnma** [comment]
is it still confusing after those two things?

**Comment by mckern** [comment]
Yep. It looks like multiple ways to get to the same basic operations on VMs.

**Comment by mckern** [comment]
(Free range organic tool, that's what this is)
