### ISSUE TITLE
VMPOOL_TOKEN doesn't get around need for LDAP password

### ISSUE THREAD

**Issue by nfagerlund** [stahnma/vmpool-cli#7]
I set the VMPOOL_TOKEN environment variable to a pre-existing token, but `vmpool` still refuses to do anything unless the LDAP_PASSWORD var is set. 

As far as I can tell from a tiny peek at the source, it's probably _using_ the token from the environment, but it's still checking for a password before checking for a token. 

It'd be nice to avoid the need for a password completely, if there's already a token in place.

**Comment by stahnma** [comment]
Yeah, confirmed. I'll hack up a fix as soon as I get a chance.

**Comment by nfagerlund** [comment]
\o/
